# Generated by Django 4.0.2 on 2022-03-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=320)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(default='null', max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default='True')),
            ],
            options={
                'db_table': 'Sign_Up',
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('valid_upto', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TOKEN', to='djangochat.signup')),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('failed_attempt_time', models.DateTimeField(blank=True, null=True)),
                ('last_login_on', models.DateTimeField(blank=True, null=True)),
                ('last_reset_on', models.DateTimeField(blank=True, null=True)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('last_reset_time', models.TimeField(blank=True, null=True)),
                ('unlocks_on', models.DateTimeField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('passwords_changed', models.IntegerField(default=0)),
                ('isdefault', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PASSWORD', to='djangochat.signup')),
            ],
            options={
                'db_table': 'passwords',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forgot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('isactive', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RESETS', to='djangochat.signup')),
            ],
            options={
                'db_table': 'password_reset_logs',
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('changed_on', models.DateTimeField(auto_now_add=True)),
                ('new_password', models.CharField(blank=True, max_length=255, null=True)),
                ('old_password', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangochat.signup')),
            ],
            options={
                'db_table': 'passwords_history',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('description', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=400)),
                ('time', models.TimeField()),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='djangochat.signup')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='djangochat.signup')),
            ],
            options={
                'db_table': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='LoginLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('login_status', models.BooleanField(blank=True, null=True)),
                ('cause', models.CharField(blank=True, max_length=255, null=True)),
                ('log_date', models.DateTimeField(blank=True, null=True)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('postal', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('region_code', models.CharField(blank=True, max_length=255, null=True)),
                ('request_page', models.CharField(blank=True, max_length=255, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=255, null=True)),
                ('isactive', models.IntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ATTEMPTS', to='djangochat.signup')),
            ],
            options={
                'db_table': 'login_logs',
            },
        ),
    ]
